# Central galaxy count parameters
Mmin: 1.0e+08
sigmaM: 0.0 

# Satellite galaxy count parameters
M0: 1.0e+06 
M1: 1.0e+12 
alpha: 0.3 

# Parameters for subhalo mass function
scaleSHMF: 0.39 
slopeSHMF: 1.91

catpath: ../test-data/z3.000/halo_info/halo_info_*.asdf 
outpath: ../test-data/galaxy_catalog/z3.000/